apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-server-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: message-server
          image: cjhjrnsczxj/message-server:02
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: message-server-service
spec:
  selector:
    app: myapp
  ports:
    - name: "18888"
      port: 18888
      targetPort: 8888
